# English translations for vigilo-turbogears.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the vigilo-turbogears
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-turbogears 3.6.0\n"
"Report-Msgid-Bugs-To: contact.vigilo@c-s.fr\n"
"POT-Creation-Date: 2015-05-21 11:47+0200\n"
"PO-Revision-Date: 2015-05-21 11:47+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/turbogears/helpers.py:89
#, python-format
msgid "Failed to get URL: %s"
msgstr "Failed to get URL: %s"

#: src/vigilo/turbogears/helpers.py:102
#, python-format
msgid ""
"Failed to convert DS %(ds)s on %(host)s: value was %(value)s (max: "
"%(max)s)"
msgstr ""
"Failed to convert DS %(ds)s on %(host)s: value was %(value)s (max: "
"%(max)s)"

#: src/vigilo/turbogears/helpers.py:133
#, python-format
msgid "high-level service \"%s\""
msgstr "high-level service \"%s\""

#: src/vigilo/turbogears/helpers.py:135
#, python-format
msgid "host \"%s\""
msgstr "host \"%s\""

#: src/vigilo/turbogears/helpers.py:137
#, python-format
msgid "service \"%(service)s\" on host \"%(host)s\""
msgstr "service \"%(service)s\" on host \"%(host)s\""

#: src/vigilo/turbogears/controllers/auth.py:34
msgid "Wrong credentials"
msgstr "Wrong credentials"

#: src/vigilo/turbogears/controllers/auth.py:65
#, python-format
msgid "Welcome back, %s!"
msgstr "Welcome back, %s!"

#: src/vigilo/turbogears/controllers/auth.py:74
msgid "We hope to see you soon!"
msgstr "We hope to see you soon!"

#: src/vigilo/turbogears/controllers/custom.py:40
#, python-format
msgid "Not a valid controller name: %s"
msgstr "Not a valid controller name: %s"

#: src/vigilo/turbogears/controllers/custom.py:51
#, python-format
msgid "%(entry)s is not a subclass of %(base)s"
msgstr "%(entry)s is not a subclass of %(base)s"

#: src/vigilo/turbogears/controllers/error.py:30
msgid "We're sorry but we weren't able to process this request."
msgstr "We're sorry but we weren't able to process this request."

#: src/vigilo/turbogears/controllers/proxy.py:134
#, python-format
msgid ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""
msgstr ""
"No server configured to monitor high-level services for application "
"\"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:149
#, python-format
msgid "No such monitored host: %s"
msgstr "No such monitored host: %s"

#: src/vigilo/turbogears/controllers/proxy.py:168
#, python-format
msgid "Access denied to host \"%(host)s\" and service \"%(service)s\""
msgstr "Access denied to host \"%(host)s\" and service \"%(service)s\""

#: src/vigilo/turbogears/controllers/proxy.py:174
#, python-format
msgid "Access denied to host \"%s\""
msgstr "Access denied to host \"%s\""

#: src/vigilo/turbogears/controllers/proxy.py:192
#, python-format
msgid "No server configured to monitor \"%(host)s\" for application \"%(app)s\""
msgstr "No server configured to monitor \"%(host)s\" for application \"%(app)s\""

#: src/vigilo/turbogears/controllers/proxy.py:227
#, python-format
msgid "Invalid value for app_redirect.%s, not redirecting."
msgstr "Invalid value for app_redirect.%s, not redirecting."

#: src/vigilo/turbogears/controllers/proxy.py:233
#, python-format
msgid "Fetching '%s' through the proxy"
msgstr "Fetching '%s' through the proxy"

#: src/vigilo/turbogears/controllers/proxy.py:256
msgid "Basic authentication to the proxy."
msgstr "Basic authentication to the proxy."

#: src/vigilo/turbogears/controllers/proxy.py:259
msgid "Digest authentication to the proxy."
msgstr "Digest authentication to the proxy."

#: src/vigilo/turbogears/controllers/proxy.py:276
msgid "Basic authentication to the website."
msgstr "Basic authentication to the website."

#: src/vigilo/turbogears/controllers/proxy.py:279
msgid "Digest authentication to the website."
msgstr "Digest authentication to the website."

#: src/vigilo/turbogears/controllers/selfmonitoring.py:36
#: src/vigilo/turbogears/controllers/api/root.py:63
msgid "You need to be authenticated"
msgstr "You need to be authenticated"

#: src/vigilo/turbogears/controllers/selfmonitoring.py:40
#, python-format
msgid "You don't have access to %s"
msgstr "You don't have access to %s"

#: src/vigilo/turbogears/controllers/selfmonitoring.py:49
#, python-format
msgid "Vigilo has detected a breakdown on the following collector(s): %(list)s"
msgstr "Vigilo has detected a breakdown on the following collector(s): %(list)s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:147
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:161
#, python-format
msgid "Remote user: %s"
msgstr "Remote user: %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:165
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:179
msgid "Beaker must be present in the WSGI middleware stack for the cache to work"
msgstr "Beaker must be present in the WSGI middleware stack for the cache to work"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:179
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:193
msgid "Exception while contacting LDAP server"
msgstr "Exception while contacting LDAP server"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:199
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:213
#, python-format
msgid "New user created: %s"
msgstr "New user created: %s"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:203
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:217
msgid "Exception during user creation"
msgstr "Exception during user creation"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:212
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:226
#, python-format
msgid "Removing user \"%(user)s\" from group \"%(group)s\""
msgstr "Removing user \"%(user)s\" from group \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:239
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:253
#, python-format
msgid "Creating group \"%s\""
msgstr "Creating group \"%s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:247
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:261
#, python-format
msgid "Adding user \"%(user)s\" to group \"%(group)s\""
msgstr "Adding user \"%(user)s\" to group \"%(group)s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:264
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:278
msgid "Exception during groups creation"
msgstr "Exception during groups creation"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:292
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:306
#, python-format
msgid "Attempting connection to \"%s\""
msgstr "Attempting connection to \"%s\""

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:320
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:334
#, python-format
msgid "Could not connect to LDAP server '%s', trying next server"
msgstr "Could not connect to LDAP server '%s', trying next server"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:325
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:339
msgid "No more LDAP servers to try"
msgstr "No more LDAP servers to try"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync.py:369
#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:393
#, python-format
msgid "User \"%s\" not found in the LDAP server"
msgstr "User \"%s\" not found in the LDAP server"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:366
#, python-format
msgid "Bound to the LDAP server as '%s'"
msgstr "Bound to the LDAP server as '%s'"

#: src/vigilo/turbogears/repoze/plugins/mdldapsync2.py:418
#, python-format
msgid "Could not retrieve groups from LDAP server for \"%s\""
msgstr "Could not retrieve groups from LDAP server for \"%s\""

#: src/vigilo/turbogears/rum/fields/group_relation.py:126
#: src/vigilo/turbogears/rum/fields/group_relation.py:150
msgid "Groups of monitored items"
msgstr "Groups of monitored items"

#: src/vigilo/turbogears/rum/fields/group_relation.py:129
#: src/vigilo/turbogears/rum/fields/group_relation.py:155
msgid "Groups of maps"
msgstr "Groups of maps"

